{% set name = "r-stitch" %}
{% set version = "1.8.1" %}
{% set sha256 = "dbcb8714d50154f7b929a3c4fc0a977a252bb4c814fe66a51e90eb8a8d798315" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  - url: https://github.com/rwdavies/STITCH/archive/refs/tags/{{ version }}.tar.gz
    sha256: '{{ sha256 }}'

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('r-stitch', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - pkg-config
    - make
    - libcxx >=16  # [osx]
  host:
    - r-base
    - r-rcpp >=1.0.14
    - r-rcpparmadillo >=0.8.600.0.0
    - r-data.table >=1.11.8
    - r-rrbgen >=0.0.6
    - r-vcfppR >=0.7.6
    - xz
    - gmp
    - mpfr
    - mpc >=1.1.0
    - libblas
    - zlib
    - libcxx >=16  # [osx]
  run:
    - r-base
    - r-rcpp >=0.12.18
    - r-rcpparmadillo >=0.8.600.0.0
    - r-data.table >=1.11.8
    - r-rrbgen >=0.0.6
    - r-vcfppR >=0.7.6
    - r-optparse
    - r-testthat >=3.0.0
    - htslib >=1.21
    - samtools >=1.21
    - rsync

test:
  commands:
    - $R -e "library('STITCH');  testthat::test_package('STITCH', stop_on_failure = TRUE, stop_on_warning = FALSE, filter = 'acceptance-one', reporter = 'summary')"
    - 'STITCH.R --help'

about:
  home: https://github.com/rwdavies/stitch
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "STITCH - Sequencing To Imputation Through Constructing Haplotypes."
  doc_url: https://github.com/rwdavies/stitch
  dev_url: https://github.com/rwdavies/stitch

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - Zilong-Li
    - rwdavies
