{% set name = "pcaone" %}
{% set version = "0.5.0" %}
{% set sha256 = "ea1fb40c2c216d7a4eb8d16184c411f5219b25c321bc872141ae920220dea35f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Zilong-Li/PCAone/archive/refs/tags/v{{ version }}.tar.gz  # [x86_64]
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pcaone', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - sysroot_linux-64 2.17  # [linux]
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - mkl
    - mkl-include
    - zlib
  run:
    - mkl
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

test:
  commands:
    - PCAone --help

about:
  home: "https://github.com/Zilong-Li/PCAone"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  summary: "PCAone - Principal Component Analysis All in One."
  doc_url: "https://github.com/Zilong-Li/PCAone"
  dev_url: "https://github.com/Zilong-Li/PCAone"

extra:
  recipe-maintainers:
    - Zilong
