{% set name = "pcaone" %}
{% set version = "0.5.1" %}
{% set sha256 = "fe89062ce89df4d19aed0c2a7d0dcf34c82d9a642bc07f4d7596cc70ef6365d5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Zilong-Li/PCAone/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pcaone', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - sysroot_linux-64 2.17  # [linux]
  host:
    - mkl >=2025.1.0
    - mkl-include >=2025.1.0
    - zlib
    - llvm-openmp # [osx]
    - libgomp # [linux]
  run:
    - mkl >=2025.1.0
    - mkl-include >=2025.1.0
    - llvm-openmp # [osx]
    - libgomp # [linux]

test:
  commands:
    - PCAone --help

about:
  home: "https://github.com/Zilong-Li/PCAone"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  summary: "PCAone - Principal Component Analysis All in One."
  doc_url: "https://github.com/Zilong-Li/PCAone"
  dev_url: "https://github.com/Zilong-Li/PCAone"

extra:
  recipe-maintainers:
    - Zilong
